apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    name: ui-deployment
    app: micro-shop
spec:
  selector:
    matchLabels:
      name: ui-pod
      app: micro-shop
  replicas: 1
  template:
    metadata:
      name: ui-pod
      labels:
        name: ui-pod
        app: micro-shop
    spec:
      restartPolicy: Always
      containers:
      - name: ui
        image: tejas9018/micro-shop-ui:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        env:
        - name: REACT_APP_API_GATEWAY
          valueFrom:
            configMapKeyRef:
              name: services-configmap
              key: api_service_url


