apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume # Sets PV's name
  labels:
    type: local # Sets PV's type to local
    app: micro-shop
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/kubernetes/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    name: postgres-pvc
    app: micro-shop
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce # Adjust this based on your requirements
  resources:
    requests:
      storage: 5Gi # Adjust the storage size as needed
