apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    name: products-deployment
    app: micro-shop
spec:
  selector:
    matchLabels:
      name: products-pod
      app: micro-shop
  replicas: 1
  template:
    metadata:
      name: products-pod
      labels:
        name: products-pod
        app: micro-shop
    spec:
      restartPolicy: Always
      containers:
      - name: products
        image: tejas9018/micro-shop-products:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8082
          name: http
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_USER_PG
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db-root-username
        - name: DATABASE_PASSWORD_PG
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db-root-password
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: database_url
        - name: DATABASE_PORT_PG
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: database_port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: products_database_name
        - name: USE_MYSQL
          valueFrom:
            configMapKeyRef:
              name: select-db-configmap
              key: use_mysql
        - name: PORT
          value: "8082"


