apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: micro-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: micro-shop
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: micro-shop
    spec:
      restartPolicy: Always
      containers:
      - name: postgres
        image: postgres
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db-root-password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres

      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
