apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  labels:
    name: postgres-db-service
    app: micro-shop
spec:
  type: LoadBalancer
  selector:
    name: postgres-pod
    app: micro-shop
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
